version: "3.7"

services:
  db:
    extends:
      file: composes/docker-compose-db.yml
      service:
        - redis
        - elastic
        - logstash

  cluster:
    extends:
      file: composes/docker-compose-cluster.yml
      service:
        - master
        - proxy
        - agent

#networks:
#  cluster:
#    ipam:
#      driver: default
#      config:
#        - subnet: "172.16.238.0/24"
#        - subnet: "2001:3984:3989::/64"