db:
#    logstash:
#      build: logstash/
#      dockerfile: ./logstash/base.master.Dockerfile
#      image: monitoring:logstash
#      command: systemctl start logstash
#      network_mode: host
#      ports:
#        - 9600

#    elastic:
#      build: .elastic
#      dockerfile: .elastic/base.master.Dockerfile
#      image: monitoring:elastic
#      network_mode: host
#      ports:
#        - 5000

#    redis:
#      build: .rerdis
#      dockerfile: .redis/base.master.Dockerfile
#      image: monitoring:redis
#      network_mode: host
#      ports:
#        - 6379
