node:
  &base:
    build:
    dockerfile: base.Dockerfile
    environment:
      - RABBITMQ_VERSION: 3.6.1
      - GOLANG_VERSION: 1.14.1
      - ERL_EPMD_PORT: 4369
      - SERVICE: base
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
    network_mode: container
    ports:
      - 5672
      - 15672

agent <<: *base
SERVICE: agent
depends_on:
  - proxy

proxy <<: *base
SERVICE: proxy
ports:
  - 4369
  - 5672
  - 15672
    #    depends_on:
    #      - master

master <<: *base
SERVICE: master
ports:
  - 5000
  - 5672
  - 4430
  - 8000
#   depends_on:
#      - db